INSERT INTO Courses (course_name, course_professor_id)
VALUE
('Surviving the Coming Zombie Apocalypse', '10'),
('The Art of Walking', '9'),
('Introduction to Beekeeping', '5'),
('The Science of Harry Potter', '10'),
('Lemonade', '2'),
('Coffee 101', '4'),
('How to Stage a Revolution', '2'),
('The #selfie', '8'),
('Tightwaddery, Or the Good Life on a Dollar a Day', '10'),
('The Politics of Kanye West', '2'),
('Patternmaking For Dog Garments', '8'),
('Wasting Time on the Internet', '1'),
('Accounting/Finance', '9'),
('Art/Design', '2'),
('Business/Business Management', '2'),
('Communication/Speech', '1'),
('History', '4'),
('Journalism/Writing', '1'),
('Physical Education', '10'),
('Political Science', '6'),
('Sciences', '7'),
('Statistics', '4'),
('Computer Science', '10'),
('Web Design/Development', '7');